### ISSUE TITLE
Error  SSL Check

### ISSUE THREAD

**Issue by kernelkill** [0xhav0c/MailSecOps#1]
Hello,

When I run option 3 and type the domain, it returns the error SSL, why?

![erro_ssl](https://github.com/user-attachments/assets/41dbd32c-4403-4e0e-9c68-cef184056448)

**Comment by 0xhav0c** [comment]
Hello!

Thank you for reporting the issue. I'm unable to replicate the SSL error on my end, so it might be specific to your environment. Here are a few questions and suggestions to help us investigate further:

![CleanShot 2024-11-14 at 23 37 58](https://github.com/user-attachments/assets/d31eb22e-dc39-43d5-bcc6-956c440587bc)


Could you please share more details about the environment you’re using (e.g., OS, Python version, and any specific configurations)?
Have you installed all required dependencies as listed in the README?
It might also help to try running the script with elevated privileges or check if there's a proxy or firewall affecting SSL verification.
Let me know if any of these resolve the issue, and we can troubleshoot further if needed. Thanks!

**Comment by kernelkill** [comment]
TKS bro, now it's worked.
I've changed the environment installed the dependencies and worked.

![image](https://github.com/user-attachments/assets/b536232a-bbda-426e-84ba-4a85782bdfc7)

Issue resolved!

**Comment by 0xhav0c** [comment]
Great 👑
